// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTL89x5xqN-Br113Om1sx0LV7ibE-yLEo',
    appId: '1:581941386127:web:8997997f5b1492ec50c9fa',
    messagingSenderId: '581941386127',
    projectId: 'moviemuse-2bc27',
    authDomain: 'moviemuse-2bc27.firebaseapp.com',
    storageBucket: 'moviemuse-2bc27.firebasestorage.app',
    measurementId: 'G-FC1BR7PF53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTL89x5xqN-Br113Om1sx0LV7ibE-yLEo',
    appId: '1:581941386127:android:your-android-app-id',
    messagingSenderId: '581941386127',
    projectId: 'moviemuse-2bc27',
    storageBucket: 'moviemuse-2bc27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTL89x5xqN-Br113Om1sx0LV7ibE-yLEo',
    appId: '1:581941386127:ios:your-ios-app-id',
    messagingSenderId: '581941386127',
    projectId: 'moviemuse-2bc27',
    storageBucket: 'moviemuse-2bc27.firebasestorage.app',
    iosBundleId: 'com.example.moviePicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTL89x5xqN-Br113Om1sx0LV7ibE-yLEo',
    appId: '1:581941386127:macos:your-macos-app-id',
    messagingSenderId: '581941386127',
    projectId: 'moviemuse-2bc27',
    storageBucket: 'moviemuse-2bc27.firebasestorage.app',
    iosBundleId: 'com.example.moviePicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTL89x5xqN-Br113Om1sx0LV7ibE-yLEo',
    appId: '1:581941386127:web:8997997f5b1492ec50c9fa',
    messagingSenderId: '581941386127',
    projectId: 'moviemuse-2bc27',
    authDomain: 'moviemuse-2bc27.firebaseapp.com',
    storageBucket: 'moviemuse-2bc27.firebasestorage.app',
    measurementId: 'G-FC1BR7PF53',
  );
} 