// Mocks generated by Mockito 5.4.6 from annotations
// in movie_picker/test/widgets/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:movie_picker/models/movie.dart' as _i6;
import 'package:movie_picker/models/user_preferences.dart' as _i2;
import 'package:movie_picker/services/movie_service.dart' as _i4;
import 'package:movie_picker/services/privacy_service.dart' as _i10;
import 'package:movie_picker/services/recommendation_service.dart' as _i7;
import 'package:movie_picker/services/secure_storage_service.dart' as _i9;
import 'package:movie_picker/services/user_data_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserPreferences_0 extends _i1.SmartFake
    implements _i2.UserPreferences {
  _FakeUserPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserData_1 extends _i1.SmartFake implements _i3.UserData {
  _FakeUserData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i4.MovieService {
  MockMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get cacheSize =>
      (super.noSuchMethod(Invocation.getter(#cacheSize), returnValue: 0)
          as int);

  @override
  bool get hasEnoughMovies =>
      (super.noSuchMethod(
            Invocation.getter(#hasEnoughMovies),
            returnValue: false,
          )
          as bool);

  @override
  void setRecommendationService(dynamic recommendationService) =>
      super.noSuchMethod(
        Invocation.method(#setRecommendationService, [recommendationService]),
        returnValueForMissingStub: null,
      );

  @override
  void setUserService(dynamic userService) => super.noSuchMethod(
    Invocation.method(#setUserService, [userService]),
    returnValueForMissingStub: null,
  );

  @override
  void setLanguage(String? language) => super.noSuchMethod(
    Invocation.method(#setLanguage, [language]),
    returnValueForMissingStub: null,
  );

  @override
  void setVoteAverageRange(double? min, double? max) => super.noSuchMethod(
    Invocation.method(#setVoteAverageRange, [min, max]),
    returnValueForMissingStub: null,
  );

  @override
  void setReleaseYear(int? year) => super.noSuchMethod(
    Invocation.method(#setReleaseYear, [year]),
    returnValueForMissingStub: null,
  );

  @override
  void setRuntimeRange(int? min, int? max) => super.noSuchMethod(
    Invocation.method(#setRuntimeRange, [min, max]),
    returnValueForMissingStub: null,
  );

  @override
  void setReleaseStatus(String? status) => super.noSuchMethod(
    Invocation.method(#setReleaseStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  void setPerson(String? person, String? personType) => super.noSuchMethod(
    Invocation.method(#setPerson, [person, personType]),
    returnValueForMissingStub: null,
  );

  @override
  void resetFilters() => super.noSuchMethod(
    Invocation.method(#resetFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> preloadMovies({
    int? targetCount = 200,
    List<String>? preferredGenres,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#preloadMovies, [], {
              #targetCount: targetCount,
              #preferredGenres: preferredGenres,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Movie>> findMoviesWithFilters({
    List<String>? selectedGenres,
    String? language,
    String? timePeriod,
    double? minRating,
    Set<int>? excludeIds,
    int? targetCount = 100,
    int? maxPages = 500,
    String? person,
    String? personType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findMoviesWithFilters, [], {
              #selectedGenres: selectedGenres,
              #language: language,
              #timePeriod: timePeriod,
              #minRating: minRating,
              #excludeIds: excludeIds,
              #targetCount: targetCount,
              #maxPages: maxPages,
              #person: person,
              #personType: personType,
            }),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  _i5.Future<List<_i6.Movie>> filterCachedMovies({
    List<String>? selectedGenres,
    String? language,
    String? timePeriod,
    double? minRating,
    Set<int>? excludeIds,
    String? person,
    String? personType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterCachedMovies, [], {
              #selectedGenres: selectedGenres,
              #language: language,
              #timePeriod: timePeriod,
              #minRating: minRating,
              #excludeIds: excludeIds,
              #person: person,
              #personType: personType,
            }),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  _i5.Future<void> maybePreloadMore({
    int? threshold = 50,
    List<String>? preferredGenres,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#maybePreloadMore, [], {
              #threshold: threshold,
              #preferredGenres: preferredGenres,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<String> getAllGenres() =>
      (super.noSuchMethod(
            Invocation.method(#getAllGenres, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<List<String>> fetchCast(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCast, [movieId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, dynamic>> fetchCastAndCrew(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCastAndCrew, [movieId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> movieHasPerson(
    int? movieId,
    String? personName,
    String? personType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#movieHasPerson, [
              movieId,
              personName,
              personType,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.Movie>> searchMoviesByPerson(
    String? personName, {
    int? personId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchMoviesByPerson,
              [personName],
              {#personId: personId},
            ),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  _i5.Future<Map<String, dynamic>?> getPersonDetails(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonDetails, [personId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<String>> fetchMovieKeywords(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieKeywords, [movieId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> fetchKeywordsForMovies(List<_i6.Movie>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKeywordsForMovies, [movies]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Movie>> getFilteredMovies({
    List<String>? selectedGenres,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredMovies, [], {
              #selectedGenres: selectedGenres,
              #refresh: refresh,
            }),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  _i5.Future<List<_i6.Movie>> loadSpecificPage({
    List<String>? selectedGenres,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadSpecificPage, [], {
              #selectedGenres: selectedGenres,
              #page: page,
            }),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  double getMovieScore(_i6.Movie? movie) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieScore, [movie]),
            returnValue: 0.0,
          )
          as double);

  @override
  bool isHighQualityMovie(_i6.Movie? movie) =>
      (super.noSuchMethod(
            Invocation.method(#isHighQualityMovie, [movie]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i6.Movie> sortMoviesByQuality(
    List<_i6.Movie>? movies, {
    dynamic userPreferences,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sortMoviesByQuality,
              [movies],
              {#userPreferences: userPreferences},
            ),
            returnValue: <_i6.Movie>[],
          )
          as List<_i6.Movie>);

  @override
  _i5.Future<List<_i6.Movie>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  double scoreMovie(_i6.Movie? movie, {required dynamic userPreferences}) =>
      (super.noSuchMethod(
            Invocation.method(
              #scoreMovie,
              [movie],
              {#userPreferences: userPreferences},
            ),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [RecommendationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationService extends _i1.Mock
    implements _i7.RecommendationService {
  MockRecommendationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserPreferences get userPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#userPreferences),
            returnValue: _FakeUserPreferences_0(
              this,
              Invocation.getter(#userPreferences),
            ),
          )
          as _i2.UserPreferences);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordInteractionForUser({
    required String? userId,
    required _i6.Movie? movie,
    required String? interactionType,
    double? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordInteractionForUser, [], {
              #userId: userId,
              #movie: movie,
              #interactionType: interactionType,
              #rating: rating,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordInteraction({
    required _i6.Movie? movie,
    required String? interactionType,
    double? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordInteraction, [], {
              #movie: movie,
              #interactionType: interactionType,
              #rating: rating,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  double calculateRecommendationScoreForUser(
    _i6.Movie? movie,
    _i2.UserPreferences? userPrefs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRecommendationScoreForUser, [
              movie,
              userPrefs,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateRecommendationScore(_i6.Movie? movie) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRecommendationScore, [movie]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i5.Future<List<_i6.Movie>> getRecommendationsForUser(
    List<_i6.Movie>? availableMovies,
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecommendationsForUser,
              [availableMovies, userId],
              {#limit: limit},
            ),
            returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]),
          )
          as _i5.Future<List<_i6.Movie>>);

  @override
  List<_i6.Movie> getRecommendations(
    List<_i6.Movie>? availableMovies, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecommendations,
              [availableMovies],
              {#limit: limit},
            ),
            returnValue: <_i6.Movie>[],
          )
          as List<_i6.Movie>);

  @override
  _i5.Future<Map<String, dynamic>> getUserInsightsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInsightsForUser, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> getUserInsights() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInsights, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearUserPreferencesCache(String? userId) => super.noSuchMethod(
    Invocation.method(#clearUserPreferencesCache, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> resetPreferencesForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#resetPreferencesForUser, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#resetPreferences, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> exportPreferencesForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#exportPreferencesForUser, [userId]),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#exportPreferencesForUser, [userId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  String exportPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#exportPreferences, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#exportPreferences, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> importPreferencesForUser(
    String? userId,
    String? preferencesJson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importPreferencesForUser, [
              userId,
              preferencesJson,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> importPreferences(String? preferencesJson) =>
      (super.noSuchMethod(
            Invocation.method(#importPreferences, [preferencesJson]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataService extends _i1.Mock implements _i3.UserDataService {
  MockUserDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserData> getCurrentUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserData, []),
            returnValue: _i5.Future<_i3.UserData>.value(
              _FakeUserData_1(this, Invocation.method(#getCurrentUserData, [])),
            ),
          )
          as _i5.Future<_i3.UserData>);

  @override
  _i5.Future<_i3.UserData> getUserData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [userId]),
            returnValue: _i5.Future<_i3.UserData>.value(
              _FakeUserData_1(this, Invocation.method(#getUserData, [userId])),
            ),
          )
          as _i5.Future<_i3.UserData>);

  @override
  _i5.Future<void> saveUserData(_i3.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userData]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> createUser(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [name]),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createUser, [name]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> switchUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#switchUser, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.UserProfile>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<List<_i3.UserProfile>>.value(
              <_i3.UserProfile>[],
            ),
          )
          as _i5.Future<List<_i3.UserProfile>>);

  @override
  _i5.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addWatchedMovie(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchedMovie, [movieId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleBookmark(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [movieId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setMovieRating(int? movieId, double? rating) =>
      (super.noSuchMethod(
            Invocation.method(#setMovieRating, [movieId, rating]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addSkippedMovie(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#addSkippedMovie, [movieId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearCurrentUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearCurrentUserData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i9.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setSecureString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSecureString, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getSecureString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSecureString, [key]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setSecureJson(String? key, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#setSecureJson, [key, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getSecureJson(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSecureJson, [key]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> removeSecure(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeSecure, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllSecureData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllSecureData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> getAllSecureData() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSecureData, []),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  String generateDataHash(String? data) =>
      (super.noSuchMethod(
            Invocation.method(#generateDataHash, [data]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateDataHash, [data]),
            ),
          )
          as String);

  @override
  bool verifyDataIntegrity(String? data, String? expectedHash) =>
      (super.noSuchMethod(
            Invocation.method(#verifyDataIntegrity, [data, expectedHash]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<Map<String, dynamic>> exportUserData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#exportUserData, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deleteUserData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserData, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PrivacyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivacyService extends _i1.Mock implements _i10.PrivacyService {
  MockPrivacyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool hasAcceptedPrivacyPolicy() =>
      (super.noSuchMethod(
            Invocation.method(#hasAcceptedPrivacyPolicy, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> acceptPrivacyPolicy() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPrivacyPolicy, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getPrivacyPolicyText() =>
      (super.noSuchMethod(
            Invocation.method(#getPrivacyPolicyText, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getPrivacyPolicyText, []),
            ),
          )
          as String);

  @override
  Map<String, dynamic> getPrivacyPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getPrivacyPreferences, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> updatePrivacyPreferences({
    int? dataRetentionDays,
    bool? analyticsEnabled,
    bool? crashReportingEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrivacyPreferences, [], {
              #dataRetentionDays: dataRetentionDays,
              #analyticsEnabled: analyticsEnabled,
              #crashReportingEnabled: crashReportingEnabled,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> exportUserData() =>
      (super.noSuchMethod(
            Invocation.method(#exportUserData, []),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#exportUserData, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> saveExportedDataToFile() =>
      (super.noSuchMethod(
            Invocation.method(#saveExportedDataToFile, []),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#saveExportedDataToFile, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteAllUserData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllUserData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic> getDataUsageStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDataUsageStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<bool> verifyDataIntegrity(String? exportedData) =>
      (super.noSuchMethod(
            Invocation.method(#verifyDataIntegrity, [exportedData]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> shouldPromptForDataRetention() =>
      (super.noSuchMethod(
            Invocation.method(#shouldPromptForDataRetention, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
